services:
  backend:
    container_name: MTG-Backend
    build:
      dockerfile: ./backend/Dockerfile
    ports:
      - "127.0.0.1:8000:8000"
    restart: always

  frontend:
    container_name: MTG-Frontend
    build:
      dockerfile: ./frontend/Dockerfile
    ports:
      - "192.168.50.142:10015:10015"
    restart: always
