networks:
  MTGPA:
    name: MTGPA
    ipam:
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1

services:
  frontend:
    container_name: MTGPA-Frontend
    build:
      dockerfile: ./frontend/Dockerfile
    ports:
      - "${HOST_IP}:10015:10015"
    environment:
      - VITE_HOST_IP=${HOST_IP}
    networks:
      MTGPA:
        ipv4_address: 172.20.0.2
    restart: always

  backend:
    container_name: MTGPA-Backend
    build:
      dockerfile: ./backend/Dockerfile
    ports:
      - "${HOST_IP}:10016:10016"
    networks:
      MTGPA:
        ipv4_address: 172.20.0.3
    restart: always
