services:
  backend:
    container_name: MTG-Backend
    build:
      dockerfile: ./backend/Dockerfile
    ports:
      - "YOUR_IP:10016:10016"
    restart: always

  frontend:
    container_name: MTG-Frontend
    build:
      dockerfile: ./frontend/Dockerfile
    ports:
      - "YOUR_IP:10015:10015"
    restart: always
